FROM node:alpine as builder

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

RUN rm .env
RUN mv docker.env .env

RUN npm run build

EXPOSE 8443

CMD [ "node", "server/server.js" ]