version: '3.1'

volumes:
  eduapp_db_data:
  nginx_data:

networks:
  common:
    driver: bridge

services:
  db:
    image: postgres:14
    env_file:
      - ./backend/eduapp_db/postgres.docker-example.env
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - common
  api:
    build:
      context: ./backend/eduapp_db
    image: eduapp/api:latest 
    env_file:
      - ./backend/eduapp_db/docker-example.env
    restart: unless-stopped
    depends_on:
      - db
    links:
      - "db:db"
    networks:
      - common
  app:
    build:
      context: ./frontend
    image: eduapp/app:latest
    env_file:
      - ./frontend/docker-example.env
    restart: unless-stopped
    ports:
      - "4010:443" # Change the first number for different port
  admin:
    build:
      context: ./eduapp-administration-panel
    image: eduapp/admin:latest
    restart: unless-stopped
    env_file:
      - ./eduapp-administration-panel/docker-example.env
    ports:
      - "5010:443" # Change the first number for different port
    networks:
    - common
  nginx:
    build:
      context: .
      dockerfile: ./Ports-Dockerfile
    image: eduapp/nginx:latest
    ports: 
      # - "80:80" # Exposes http so that it redirects to 443 if configured
      - "3010:443" # Change the first number for different port
    depends_on:
      - api
    volumes:
      - nginx_data:/etc/nginx/conf.d
    links:
      - "api:api"
    networks:
      - common