version: '3.1'

#############################################################
# NOT CONFIGURED FOR PUBLIC USE. PLEASE USE BYPORTS-COMPOSE #
#############################################################

# volumes:
#   eduapp_db_data:
#   nginx_data:

# networks:
#   common:
#     driver: bridge

# services:
#   db:
#     image: postgres:14
#     env_file:
#       - ./backend/eduapp_db/postgres.production.env
#     volumes:
#       - eduapp_db_data:/var/lib/postgresql/data/pgdata
#     restart: unless-stopped
#     networks:
#       - common
#   api:
#     build:
#       context: ./backend/eduapp_db
#     image: eduapp/api:latest 
#     env_file:
#       - ./backend/eduapp_db/production.env
#     restart: unless-stopped
#     depends_on:
#       - db
#     links:
#       - "db:db"
#     networks:
#       - common
#   app:
#     build:
#       context: ./frontend
#     image: eduapp/app:latest
#     env_file:
#       - ./frontend/.env
#     restart: unless-stopped
#   admin:
#     build:
#       context: ./eduapp-administration-panel
#     image: eduapp/admin:latest
#     env_file:
#       - ./eduapp-administration-panel/.env
#     restart: unless-stopped
#     networks:
#     - common
#   nginx:
#     build:
#       context: .
#       dockerfile: ./Subdomain-Dockerfile
#     image: eduapp/nginx:latest
#     ports: 
#       - "8443:443" # Change the first number for different port
#     depends_on:
#       - api
#     volumes:
#       - nginx_data:/etc/nginx/conf.d
#     links:
#       - "api:api"
#       - "app:app"
#       - "admin:admin"
#     networks:
#       - common