FROM ruby:2.6.9

WORKDIR /backend

COPY package*.json ./
COPY Gemfile* ./

ENV RAILS_SECRET_KEY="599fef69235287bd8c268db895897f236aebf4f63971aa48f48e3ee81c5612006a4857751cb1859546ccde67bb84cb3cc799a6aa9196b036d9a872dcd7765809" \
	ENCRYPTION_SALT="81IJngXK2FE1+1J2Ugs1VxuK0yTnUyZQCSFbv0SUNRgZpMN7EN8SzoeSDuD+\nOXU0cwQyoFaAgfsckvz0di4SIyxHZs0OWey32Y5VI6Dg8rTNR8q2Z+oIv4tS\n2DOYeQ56uax3nQ/A+JikqvsLAfZYjhe3OpB5GUlgeJFnA30xB68Ock3HSInI\nW1kuZxN8dQu2eGwPT+3iNR9/DHe0Zku3G5MtZNzciHAT04JXVP+YXVraLVv1\nj5ctdDmWx1shNoBidO3q6PS+0peInRJmChVHcfoaBbhQuF2hv5vv5Qcd/c0f\nUDOWqho2DrA3hYm252t5BWTjfNoI3p7M0E1KRHmZDQ==\n" \
	ENCRYPTION_PATTERN="#_::_#"\
	RAILS_ENV=production\
	API_VERSION="v1"\
	# POSTGRES CONFIG
	PROD_DB_USER=eduapp_prod\
	PROD_DB_PSWD=prod_eduapp_22\
	PROD_DB_PORT=5432\
	# HOSTING CONFIG
	PORT=3000\
	HOST=db\
	DOMAIN="localhost"\
	HOST_DOMAIN="$DOMAIN:$PORT/api/$API_VERSION"\
	# FRONTEND ENPOINT FOR CORS
	REACT_APP_FRONTEND_ENDPOINT=https://eduapp-online.web.app/\
	REACT_APP_ADMIN_ENDPOINT=https://eduapp-admin.web.app/\
	# EMAIL
	SMTP_PORT=587\
	SMTP_ADDRESS=smtp.gmail.com\
	GMAIL_USERNAME=eduappdevelopment@gmail.com\
	GMAIL_PASSWORD=edurincondevs2021

RUN gem install bundler
RUN bundle install

COPY . .

RUN rm -f ./tmp/pids/server.pid

EXPOSE 3000

# CMD [ "rails", "s" , "-b", "ssl://0.0.0.0:3000?key=./.cert/eduapp.key&cert=./.cert/eduapp.crt" ]
CMD [ "rails", "s", "-b", "0.0.0.0" ]