source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.8'


gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'devise'
gem 'devise-jwt'
gem 'rack-cors' , :require =>'rack/cors'
gem 'ransack'
gem 'image_processing', '~> 1.2'
gem 'active_model_serializers'
gem 'bootsnap', '>= 1.4.4', require: false



group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
group :test do 
  gem 'rspec-rails'
end
group :development do
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
